IF(NOT submodule_FOUND)	
	SET(SP_INTERFACE_PATH "${MY_ROOT_DIR}/modules/Interface")
	SET(SPACENET_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/spacenet")
	SET(SPACENET_OD_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/spaceod")
	SET(COMM_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/comm")
	SET(FW_SDK_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/framework")
	SET(FW_BASE_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/frameworkbase")
	SET(AVPMAP_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/avp_map")
	SET(BEHAVIORLAYER_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/behaviorlayer")
	SET(PLD_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/pld")
	SET(SEG_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/seg")
	SET(SEGPARSE_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/segparse")
	SET(APA_COMM_MATH_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/apa_comm_math")
	SET(APA_PATH_PLAN "${MY_ROOT_DIR}/space_modules/avp_waic_demo/apa_pathplan")
	SET(GRID_MAP "${MY_ROOT_DIR}/space_modules/avp_waic_demo/comm/thirdparty/libgridmap")
	SET(PATH_FOLLOW "${MY_ROOT_DIR}/space_modules/avp_waic_demo/pathfollow")
	SET(PARKOCCUPY "${MY_ROOT_DIR}/space_modules/avp_waic_demo/parkoccupy")
	SET(PATH_PLAN "${MY_ROOT_DIR}/space_modules/avp_waic_demo/pathplan")
	SET(LIB_PATH_FOLLOW "${MY_ROOT_DIR}/space_modules/avp_waic_demo/lib_path_follow")
	SET(APA_MODULE "${MY_ROOT_DIR}/space_modules/avp_waic_demo/apa_module")
	SET(COM_DR "${MY_ROOT_DIR}/space_modules/avp_waic_demo/comdr")
	SET(CAN "${MY_ROOT_DIR}/space_modules/avp_waic_demo/can")
	SET(TSML_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/tsml")
	SET(SLAM_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/slam/core")
	SET(AVPMAPONLINESCHEDULER_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/avp_online_map_scheduler")
	SET(LIB_G2O "${MY_ROOT_DIR}/space_modules/avp_waic_demo/slam/core/3rdparty/g2o")
    SET(NETWORK_CONNECTOR_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/network_connector")
	SET(SCHEDULER_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/scheduler")
	SET(VEHICLECONTROL_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/vehiclecontrol")
	SET(ODHMI_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/odhmi")
	SET(MDF_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/mdf")
	SET(PARKOUT_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/parkout")
	SET(AVP_BEHAVIORHSM_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/avp_behaviorHSM")
	SET(AVP_PATHPLAN_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/avp_pathplan")
	SET(SPM_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/spacemap")
	SET(CLOUD_CONNECTOR_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/cloudconnector")
	SET(DAFW_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/daframework")
	SET(SPACE_AUTOPILOT_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo")
	SET(ROS_BRIDGE_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/RosBridge")
	SET(LIDAR_DETECT_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/lidar_detect")
	
	#SET(OPENCV_300_PATH "/horizon_x3_tc/samples/02_runtime_src/deps/aarch64/opencv")
	SET(submodule_FOUND TRUE)
ENDIF()
	
	
