IF(NOT submodule_FOUND)	
	SET(MY_ROOT_DIR "/home/space_sw/workspace/tda4/space_dev/ti_tda4")
	SET(SP_INTERFACE_PATH "${MY_ROOT_DIR}/modules/Interface")
	SET(COMM_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/comm")
	SET(FW_SDK_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/framework")
	SET(FW_BASE_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/frameworkbase")
	SET(AVPMAP_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/avp_map")
	SET(PLD_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/pld")
	SET(SEG_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/seg")
	SET(SEGPARSE_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/segparse")
	SET(APA_COMM_MATH_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/apa_comm_math")
	SET(APA_PATH_PLAN "${MY_ROOT_DIR}/space_modules/avp_waic_demo/apa_pathplan")
	SET(GRID_MAP "${MY_ROOT_DIR}/space_modules/avp_waic_demo/comm/thirdparty/libgridmap")
	SET(PATH_FOLLOW "${MY_ROOT_DIR}/space_modules/avp_waic_demo/pathfollow")
	SET(PARKOCCUPY "${MY_ROOT_DIR}/space_modules/avp_waic_demo/parkoccupy")
	SET(LIB_PATH_FOLLOW "${MY_ROOT_DIR}/space_modules/avp_waic_demo/lib_path_follow")
	SET(APA_MODULE "${MY_ROOT_DIR}/space_modules/avp_waic_demo/apa_module")
	SET(COM_DR "${MY_ROOT_DIR}/space_modules/avp_waic_demo/comdr")
	SET(CAN "${MY_ROOT_DIR}/space_modules/avp_waic_demo/can")
    SET(TSML_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/tsml")
	SET(LIB_G2O "${MY_ROOT_DIR}/space_modules/avp_waic_demo/slam/core/3rdparty/g2o")
	SET(NETWORK_CONNECTOR_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/network_connector")
	SET(SCHEDULER_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/scheduler")
	SET(VEHICLECONTROL_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/vehiclecontrol")
	SET(DAFW_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo/daframework")
	SET(SPACE_AUTOPILOT_PATH "${MY_ROOT_DIR}/space_modules/avp_waic_demo")
	#SET(OPENCV_300_PATH "/horizon_x3_tc/samples/02_runtime_src/deps/aarch64/opencv")
	SET(submodule_FOUND TRUE)
ENDIF()
	
	
